name: Build Pyreadr wheels

env:
  # A commit hash for the pyreadstat repo, for which to build wheels. 
  SOURCE_REF_TO_BUILD: f11ebce22fe7ae2c89de51392d7c202e33df4557

on: [push]

jobs:
  build_wheels:
    name: Build wheel ${{ matrix.python[0] }}-${{ matrix.buildplat[1] }}-${{ matrix.buildplat[2] }}
    runs-on: ${{ matrix.buildplat[0] }}
    strategy:
      # Ensure that a wheel builder finishes even if another fails
      fail-fast: false
      matrix:
        # Github Actions doesn't support pairing matrix values together, let's improvise
        # https://github.com/github/feedback/discussions/7835#discussioncomment-1769026
        buildplat:
          - [windows-2022, win_amd64, ""]
          #- [macos-15-intel, macosx_x86_64, ""]
          #- [macos-14, macosx_arm64, ""]
          #- [ubuntu-22.04, manylinux_x86_64, ""]
          #- [ubuntu-22.04-arm, manylinux_aarch64, ""]

        python:
          - ["cp312", "3.12"]
        #python: ["cp310", "cp311", "cp312", "cp313", "cp314"]

    steps:
      - name: Checkout pyreadr-wheels
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          persist-credentials: false

      - name: Checkout pyreadr
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          repository: ofajardo/pyreadr
          ref: ${{ env.SOURCE_REF_TO_BUILD }}
          path: pyreadr
          submodules: true
          persist-credentials: false

      - if: runner.os == 'Windows'
        uses: msys2/setup-msys2@v2
        id: msys2
        with:
          msystem: MINGW64
          path-type: inherit
          install: >-
            mingw-w64-x86_64-toolchain
            mingw-w64-x86_64-xz

      - name: Build wheels
        uses: pypa/cibuildwheel@9c00cb4f6b517705a3794b22395aedc36257242c  # v3.2.1
        env:
          CIBW_BUILD: ${{ matrix.python[0] }}-${{ matrix.buildplat[1] }}
          SRC: ${{ github.workspace }}/pyreadstat
          MSYS2_LOCATION: ${{ steps.msys2.outputs.msys2-location }}"
        with:
           package-dir: pyreadr
           output-dir: dist
           config-file: cibuildwheel.toml

      - uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: ${{ matrix.python[0] }}-${{ matrix.buildplat[1] }}-${{ matrix.buildplat[2] }}
          path: ./dist/*.whl

